# **ANALIKET**


Kaggle Repo: https://www.kaggle.com/patrickb1912/ipl-complete-dataset-20082020


### Liabraires


In [ ]:
import numpy as np
import pandas as pd


### Import Dataset Matches

In [ ]:
matches_sheet_id="1GLmJ5TFHSqgCoZExXVOi8_N0XUrPEb5HbjYdzgSSc7I"
matches_sheet_name="Matches"

matches= pd.read_csv("https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(matches_sheet_id,matches_sheet_name))

In [ ]:
matches 

id        city        date  ... method      umpire1         umpire2
0     335982   Bangalore  2008-04-18  ...    NaN    Asad Rauf     RE Koertzen
1     335983  Chandigarh  2008-04-19  ...    NaN    MR Benson      SL Shastri
2     335984       Delhi  2008-04-19  ...    NaN    Aleem Dar  GA Pratapkumar
3     335985      Mumbai  2008-04-20  ...    NaN     SJ Davis       DJ Harper
4     335986     Kolkata  2008-04-20  ...    NaN    BF Bowden     K Hariharan
..       ...         ...         ...  ...    ...          ...             ...
811  1216547       Dubai  2020-09-28  ...    NaN  Nitin Menon      PR Reiffel
812  1237177       Dubai  2020-11-05  ...    NaN  CB Gaffaney     Nitin Menon
813  1237178   Abu Dhabi  2020-11-06  ...    NaN   PR Reiffel          S Ravi
814  1237180   Abu Dhabi  2020-11-08  ...    NaN   PR Reiffel          S Ravi
815  1237181       Dubai  2020-11-10  ...    NaN  CB Gaffaney     Nitin Menon

[816 rows x 17 columns]

Import Dataset Deliveries

In [ ]:
deliveries_sheet_id="1q46D3MIMw_eAGN-17t9V8tTbjGDH0gHt_JHTWdSA_W8"
deliveries_sheet_name="Deliveries"

deliveries= pd.read_csv("https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(deliveries_sheet_id,deliveries_sheet_name))

In [ ]:
deliveries

id  inning  ...           batting_team                 bowling_team
0        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
1        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
2        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
3        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
4        335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
...         ...     ...  ...                    ...                          ...
193463  1237181       1  ...         Delhi Capitals               Mumbai Indians
193464  1237181       1  ...         Delhi Capitals               Mumbai Indians
193465  1237181       1  ...         Delhi Capitals               Mumbai Indians
193466  1237181       1  ...         Delhi Capitals               Mumbai Indians
193467  1237181       1  ...         Delhi Capitals               Mumbai Indians

[193468 rows x 18 columns]

In [ ]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

## **Data Cleaning and Preprocessing**

IPL Teams represents a city and if a city had been represented by multiple teams it should be count as as one. So, in order to apply this practice uniformly we are changing the team name to their cities 

In [ ]:
matches_2=matches.copy()
team1=matches_2['team1'].unique()
matches_2['team1'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['team1'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['team1'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['team1'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['team1'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['team1'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['team1'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['team1'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['team1'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['team1'].replace('Pune Warriors','Pune',inplace=True)
matches_2['team1'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['team1'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['team1'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['team1'].replace('Rising Pune Supergiant','Pune',inplace=True)
matches_2['team1'].replace('Delhi Capitals','Delhi',inplace=True)

In [ ]:
matches_2['team1'].unique()

array(['Bangalore', 'Punjab', 'Delhi', 'Mumbai', 'Kolkata', 'Rajasthan',
       'Hyderabad', 'Chennai', 'Kerala', 'Pune', 'Gujarat'], dtype=object)

In [ ]:
team2=matches_2['team2'].unique()
print(team2)
matches_2['team2'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['team2'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['team2'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['team2'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['team2'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['team2'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['team2'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['team2'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['team2'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['team2'].replace('Pune Warriors','Pune',inplace=True)
matches_2['team2'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['team2'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['team2'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['team2'].replace('Rising Pune Supergiant','Pune',inplace=True)
matches_2['team2'].replace('Delhi Capitals','Delhi',inplace=True)

['Kolkata Knight Riders' 'Chennai Super Kings' 'Rajasthan Royals'
 'Royal Challengers Bangalore' 'Deccan Chargers' 'Kings XI Punjab'
 'Delhi Daredevils' 'Mumbai Indians' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Rising Pune Supergiants'
 'Gujarat Lions' 'Rising Pune Supergiant' 'Delhi Capitals']


In [ ]:
matches_2['team2'].unique()

array(['Kolkata', 'Chennai', 'Rajasthan', 'Bangalore', 'Hyderabad',
       'Punjab', 'Delhi', 'Mumbai', 'Kerala', 'Pune', 'Gujarat'],
      dtype=object)

In [ ]:
matches_2.head(12)

id        city        date  ... method    umpire1         umpire2
0   335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1   335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2   335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3   335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4   335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan
5   335987      Jaipur  2008-04-21  ...    NaN  Aleem Dar       RB Tiffin
6   335988   Hyderabad  2008-04-22  ...    NaN  IL Howell       AM Saheba
7   335989     Chennai  2008-04-23  ...    NaN  DJ Harper  GA Pratapkumar
8   335990   Hyderabad  2008-04-24  ...    NaN  Asad Rauf       MR Benson
9   335991  Chandigarh  2008-04-25  ...    NaN  Aleem Dar       AM Saheba
10  335992   Bangalore  2008-04-26  ...    NaN  MR Benson       IL Howell
11  335993     Chennai  2008-04-26  ...    NaN  BF Bowden  AV Jayaprakash

[12 rows x 17 columns]

In [ ]:
matches_2['winner'].unique()
matches_2['winner'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['winner'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['winner'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['winner'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['winner'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['winner'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['winner'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['winner'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['winner'].replace('Pune Warriors','Pune',inplace=True)
matches_2['winner'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['winner'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['winner'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['winner'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['winner'].replace('Rising Pune Supergiant','Delhi',inplace=True)
matches_2['winner'].replace('Delhi Capitals','Delhi',inplace=True)

In [ ]:
matches_2['winner'].fillna("No Result", inplace = True)

In [ ]:
matches_2['winner'].unique()

array(['Kolkata', 'Chennai', 'Delhi', 'Bangalore', 'Rajasthan', 'Punjab',
       'Hyderabad', 'Mumbai', 'Pune', 'Kerala', 'No Result', 'Gujarat'],
      dtype=object)

In [ ]:
matches_2.head(10)

id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan
5  335987      Jaipur  2008-04-21  ...    NaN  Aleem Dar       RB Tiffin
6  335988   Hyderabad  2008-04-22  ...    NaN  IL Howell       AM Saheba
7  335989     Chennai  2008-04-23  ...    NaN  DJ Harper  GA Pratapkumar
8  335990   Hyderabad  2008-04-24  ...    NaN  Asad Rauf       MR Benson
9  335991  Chandigarh  2008-04-25  ...    NaN  Aleem Dar       AM Saheba

[10 rows x 17 columns]

In [ ]:
toss_winner=matches_2['toss_winner'].unique()
print(toss_winner)
matches_2['toss_winner'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
matches_2['toss_winner'].replace('Chennai Super Kings','Chennai',inplace=True)
matches_2['toss_winner'].replace('Rajasthan Royals','Rajasthan',inplace=True)
matches_2['toss_winner'].replace('Mumbai Indians','Mumbai',inplace=True)
matches_2['toss_winner'].replace('Deccan Chargers','Hyderabad',inplace=True)
matches_2['toss_winner'].replace('Kings XI Punjab','Punjab',inplace=True)
matches_2['toss_winner'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
matches_2['toss_winner'].replace('Delhi Daredevils','Delhi',inplace=True)
matches_2['toss_winner'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
matches_2['toss_winner'].replace('Pune Warriors','Pune',inplace=True)
matches_2['toss_winner'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
matches_2['toss_winner'].replace('Gujarat Lions','Gujarat',inplace=True)
matches_2['toss_winner'].replace('Rising Pune Supergiants','Pune',inplace=True)
matches_2['toss_winner'].replace('Rising Pune Supergiant','Pune',inplace=True)
matches_2['toss_winner'].replace('Delhi Capitals','Delhi',inplace=True)

['Royal Challengers Bangalore' 'Chennai Super Kings' 'Rajasthan Royals'
 'Mumbai Indians' 'Deccan Chargers' 'Kings XI Punjab'
 'Kolkata Knight Riders' 'Delhi Daredevils' 'Kochi Tuskers Kerala'
 'Pune Warriors' 'Sunrisers Hyderabad' 'Gujarat Lions'
 'Rising Pune Supergiants' 'Rising Pune Supergiant' 'Delhi Capitals']


In [ ]:
matches_2.head(10)

id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan
5  335987      Jaipur  2008-04-21  ...    NaN  Aleem Dar       RB Tiffin
6  335988   Hyderabad  2008-04-22  ...    NaN  IL Howell       AM Saheba
7  335989     Chennai  2008-04-23  ...    NaN  DJ Harper  GA Pratapkumar
8  335990   Hyderabad  2008-04-24  ...    NaN  Asad Rauf       MR Benson
9  335991  Chandigarh  2008-04-25  ...    NaN  Aleem Dar       AM Saheba

[10 rows x 17 columns]

In [ ]:
matches_2['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', nan, 'Rajkot', 'Kanpur', 'Bengaluru', 'Dubai',
       'Sharjah'], dtype=object)

In [ ]:
matches_2['city'].replace('Bengaluru','Bangalore',inplace=True)
matches_2['city'].fillna("Unknown City", inplace = True)
matches_2['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur',
       'Hyderabad', 'Chennai', 'Cape Town', 'Port Elizabeth', 'Durban',
       'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Kochi', 'Indore', 'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Unknown City', 'Rajkot', 'Kanpur', 'Dubai',
       'Sharjah'], dtype=object)

In [ ]:
matches_2.head()

id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['eliminator'].unique()

array(['N', 'Y', nan], dtype=object)

In [ ]:

matches_2['eliminator'].replace('N','No',inplace=True)
matches_2['eliminator'].replace('Y','Yes',inplace=True)
matches_2['eliminator'].fillna("NR", inplace = True)

In [ ]:
matches_2['eliminator'].unique()

array(['No', 'Yes', 'NR'], dtype=object)

In [ ]:
matches_2['player_of_match'].unique()

array(['BB McCullum', 'MEK Hussey', 'MF Maharoof', 'MV Boucher',
       'DJ Hussey', 'SR Watson', 'V Sehwag', 'ML Hayden', 'YK Pathan',
       'KC Sangakkara', 'JDP Oram', 'AC Gilchrist', 'SM Katich',
       'MS Dhoni', 'ST Jayasuriya', 'GD McGrath', 'SE Marsh',
       'SA Asnodkar', 'R Vinay Kumar', 'IK Pathan', 'SM Pollock',
       'Sohail Tanvir', 'S Sreesanth', 'A Nehra', 'SC Ganguly',
       'CRD Fernando', 'L Balaji', 'Shoaib Akhtar', 'A Mishra',
       'DPMD Jayawardene', 'GC Smith', 'DJ Bravo', 'M Ntini',
       'SP Goswami', 'A Kumble', 'KD Karthik', 'JA Morkel', 'P Kumar',
       'Umar Gul', 'SK Raina', 'SR Tendulkar', 'R Dravid', 'DL Vettori',
       'RP Singh', 'M Muralitharan', 'CH Gayle', 'AB de Villiers',
       'RS Bopara', 'PP Ojha', 'TM Dilshan', 'HH Gibbs', 'DP Nannes',
       'JP Duminy', 'Yuvraj Singh', 'SB Jakati', 'JH Kallis', 'G Gambhir',
       'RG Sharma', 'A Singh', 'S Badrinath', 'DR Smith', 'LRPL Taylor',
       'Harbhajan Singh', 'R Bhatia', 'SK Warne', 'B

In [ ]:
matches_2['player_of_match'].isnull().unique()

array([False,  True])

In [ ]:
matches_2['player_of_match'].fillna("No Result", inplace = True)

In [ ]:
matches_2['player_of_match'].unique()

array(['BB McCullum', 'MEK Hussey', 'MF Maharoof', 'MV Boucher',
       'DJ Hussey', 'SR Watson', 'V Sehwag', 'ML Hayden', 'YK Pathan',
       'KC Sangakkara', 'JDP Oram', 'AC Gilchrist', 'SM Katich',
       'MS Dhoni', 'ST Jayasuriya', 'GD McGrath', 'SE Marsh',
       'SA Asnodkar', 'R Vinay Kumar', 'IK Pathan', 'SM Pollock',
       'Sohail Tanvir', 'S Sreesanth', 'A Nehra', 'SC Ganguly',
       'CRD Fernando', 'L Balaji', 'Shoaib Akhtar', 'A Mishra',
       'DPMD Jayawardene', 'GC Smith', 'DJ Bravo', 'M Ntini',
       'SP Goswami', 'A Kumble', 'KD Karthik', 'JA Morkel', 'P Kumar',
       'Umar Gul', 'SK Raina', 'SR Tendulkar', 'R Dravid', 'DL Vettori',
       'RP Singh', 'M Muralitharan', 'CH Gayle', 'AB de Villiers',
       'RS Bopara', 'PP Ojha', 'TM Dilshan', 'HH Gibbs', 'DP Nannes',
       'JP Duminy', 'Yuvraj Singh', 'SB Jakati', 'JH Kallis', 'G Gambhir',
       'RG Sharma', 'A Singh', 'S Badrinath', 'DR Smith', 'LRPL Taylor',
       'Harbhajan Singh', 'R Bhatia', 'SK Warne', 'B

In [ ]:
matches_2.head()

id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['venue'].isnull().unique()

array([False])

In [ ]:
matches_2['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket St

In [ ]:
matches_2['venue'].replace('M Chinnaswamy Stadium','M.Chinnaswamy Stadium',inplace=True)
matches_2['venue'].replace('Punjab Cricket Association IS Bindra Stadium, Mohali','Punjab Cricket Association IS Bindra Stadium',inplace=True)
matches_2['venue'].replace('Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium','DYSRR International Cricket Stadium',inplace=True)


In [ ]:
matches_2['venue'].unique()

array(['M.Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium', 'DYSRR International Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharas

In [ ]:
matches_2['neutral_venue'].unique()

array([0, 1])

In [ ]:
matches_2['result'].unique()

array(['runs', 'wickets', 'tie', nan], dtype=object)

In [ ]:
matches_2['result_margin'].unique()

array([140.,  33.,   9.,   5.,   6.,   3.,  66.,   7.,  10.,   4.,  13.,
        45.,   8.,  29.,  18.,  23.,  41.,  12.,  65.,  25.,   1.,  14.,
       105.,  19.,  75.,  92.,  11.,  24.,  nan,  27.,  38.,  78.,  16.,
        53.,   2.,  31.,  55.,  98.,  34.,  36.,  39.,  17.,  40.,  67.,
        63.,  37.,  57.,  35.,  22.,  21.,  48.,  26.,  20.,  85.,  32.,
        76., 111.,  82.,  43.,  58.,  28.,  74.,  42.,  59.,  46.,  47.,
        86.,  44.,  87., 130.,  15.,  60.,  77.,  30.,  50.,  93.,  72.,
        62.,  97., 138.,  71., 144.,  80.,  51.,  61., 146.,  64., 102.,
       118.,  49.,  88.,  69.])

In [ ]:
matches_2['result_margin'].isnull().unique()

array([False,  True])

In [ ]:
matches_2['result_margin'].fillna(0, inplace = True)

In [ ]:
matches_2['result_margin'].isnull().unique()

array([False])

In [ ]:
matches_2.head()

id        city        date  ... method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...    NaN  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...    NaN  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...    NaN  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...    NaN   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...    NaN  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['eliminator'].isnull().unique()

array([False])

In [ ]:
matches_2['method'].unique()

array([nan, 'D/L'], dtype=object)

In [ ]:
matches_2['method'].fillna("Normal", inplace = True)

In [ ]:
matches_2.head()

id        city        date  ...  method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...  Normal  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...  Normal  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...  Normal  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...  Normal   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...  Normal  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['umpire1'].isnull().unique()

array([False])

In [ ]:
matches_2['umpire2'].isnull().unique()

array([False])

In [ ]:
deliveries_2 = deliveries.copy()
deliveries_2.head()

id  inning  ...           batting_team                 bowling_team
0  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
1  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
2  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
3  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore
4  335982       1  ...  Kolkata Knight Riders  Royal Challengers Bangalore

[5 rows x 18 columns]

In [ ]:
deliveries_2['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Kings XI Punjab', 'Chennai Super Kings', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [ ]:
deliveries_2['batting_team'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
deliveries_2['batting_team'].replace('Chennai Super Kings','Chennai',inplace=True)
deliveries_2['batting_team'].replace('Rajasthan Royals','Rajasthan',inplace=True)
deliveries_2['batting_team'].replace('Mumbai Indians','Mumbai',inplace=True)
deliveries_2['batting_team'].replace('Deccan Chargers','Hyderabad',inplace=True)
deliveries_2['batting_team'].replace('Kings XI Punjab','Punjab',inplace=True)
deliveries_2['batting_team'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
deliveries_2['batting_team'].replace('Delhi Daredevils','Delhi',inplace=True)
deliveries_2['batting_team'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
deliveries_2['batting_team'].replace('Pune Warriors','Pune',inplace=True)
deliveries_2['batting_team'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
deliveries_2['batting_team'].replace('Gujarat Lions','Gujarat',inplace=True)
deliveries_2['batting_team'].replace('Rising Pune Supergiants','Pune',inplace=True)
deliveries_2['batting_team'].replace('Rising Pune Supergiant','Pune',inplace=True)
deliveries_2['batting_team'].replace('Delhi Capitals','Delhi',inplace=True)

In [ ]:
deliveries_2['batting_team'].unique()

array(['Kolkata', 'Bangalore', 'Punjab', 'Chennai', 'Rajasthan', 'Delhi',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Gujarat'], dtype=object)

In [ ]:
deliveries_2['batting_team'].isnull().unique()

array([False])

In [ ]:
deliveries_2['bowling_team'].unique()

array(['Royal Challengers Bangalore', 'Kolkata Knight Riders',
       'Chennai Super Kings', 'Kings XI Punjab', 'Delhi Daredevils',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', nan,
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals'], dtype=object)

In [ ]:
deliveries_2['bowling_team'].replace('Royal Challengers Bangalore','Bangalore',inplace=True)
deliveries_2['bowling_team'].replace('Chennai Super Kings','Chennai',inplace=True)
deliveries_2['bowling_team'].replace('Rajasthan Royals','Rajasthan',inplace=True)
deliveries_2['bowling_team'].replace('Mumbai Indians','Mumbai',inplace=True)
deliveries_2['bowling_team'].replace('Deccan Chargers','Hyderabad',inplace=True)
deliveries_2['bowling_team'].replace('Kings XI Punjab','Punjab',inplace=True)
deliveries_2['bowling_team'].replace('Kolkata Knight Riders','Kolkata',inplace=True)
deliveries_2['bowling_team'].replace('Delhi Daredevils','Delhi',inplace=True)
deliveries_2['bowling_team'].replace('Kochi Tuskers Kerala','Kerala',inplace=True)
deliveries_2['bowling_team'].replace('Pune Warriors','Pune',inplace=True)
deliveries_2['bowling_team'].replace('Sunrisers Hyderabad','Hyderabad',inplace=True)
deliveries_2['bowling_team'].replace('Gujarat Lions','Gujarat',inplace=True)
deliveries_2['bowling_team'].replace('Rising Pune Supergiants','Pune',inplace=True)
deliveries_2['bowling_team'].replace('Rising Pune Supergiant','Pune',inplace=True)
deliveries_2['bowling_team'].replace('Delhi Capitals','Delhi',inplace=True)
deliveries_2['bowling_team'].fillna("Unknown", inplace = True)

In [ ]:
deliveries_2['bowling_team'].unique()

array(['Bangalore', 'Kolkata', 'Chennai', 'Punjab', 'Delhi', 'Rajasthan',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Unknown', 'Gujarat'],
      dtype=object)

In [ ]:
deliveries_2.head()

id  inning  over  ball  ... fielder extras_type batting_team  bowling_team
0  335982       1     6     5  ...     NaN         NaN      Kolkata     Bangalore
1  335982       1     6     6  ...     NaN         NaN      Kolkata     Bangalore
2  335982       1     7     1  ...     NaN         NaN      Kolkata     Bangalore
3  335982       1     7     2  ...     NaN         NaN      Kolkata     Bangalore
4  335982       1     7     3  ...     NaN         NaN      Kolkata     Bangalore

[5 rows x 18 columns]

In [ ]:
deliveries_2['inning'].isnull().unique()

array([False])

In [ ]:
deliveries_2['inning'].unique()

array([1, 2])

In [ ]:
deliveries_2['over'].isnull().unique()

array([False])

In [ ]:
deliveries_2['over'].unique()

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,  2,
        3,  4,  5])

In [ ]:
deliveries_2['ball'].isnull().unique()

array([False])

In [ ]:
deliveries_2['ball'].unique()

array([5, 6, 1, 2, 3, 4, 7, 8, 9])

In [ ]:
deliveries_2['batsman'].isnull().unique()

array([False])

In [ ]:
deliveries_2['batsman'].unique()

array(['RT Ponting', 'BB McCullum', 'DJ Hussey', 'Mohammad Hafeez',
       'SC Ganguly', 'CL White', 'MV Boucher', 'B Akhil', 'AA Noffke',
       'P Kumar', 'Z Khan', 'SB Joshi', 'W Jaffer', 'JH Kallis',
       'R Dravid', 'V Kohli', 'K Goel', 'MEK Hussey', 'JR Hopes',
       'SK Raina', 'JDP Oram', 'S Badrinath', 'PA Patel', 'ML Hayden',
       'MS Dhoni', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'T Kohli', 'YK Pathan', 'S Dhawan', 'G Gambhir',
       'SK Warne', 'D Salunkhe', 'SK Trivedi', 'V Sehwag', 'SR Watson',
       'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul',
       'LRPL Taylor', 'WP Saha', 'AS Yadav', 'A Symonds', 'SB Bangar',
       'WPUJC Vaas', 'RP Singh', 'AC Gilchrist', 'Y Venugopal Rao',
       'VVS Laxman', 'RG Sharma', 'SB Styris', 'LR Shukla', 'PP Chawla',
       'Kamran Akmal', 'DPMD Jayawardene'

In [ ]:
deliveries_2['non_striker'].isnull().unique()

array([False])

In [ ]:
deliveries_2['non_striker'].unique()

array(['BB McCullum', 'RT Ponting', 'DJ Hussey', 'Mohammad Hafeez',
       'SC Ganguly', 'MV Boucher', 'CL White', 'B Akhil', 'AA Noffke',
       'P Kumar', 'Z Khan', 'SB Joshi', 'JH Kallis', 'W Jaffer',
       'R Dravid', 'V Kohli', 'JR Hopes', 'S Badrinath', 'K Goel',
       'SK Raina', 'MEK Hussey', 'JDP Oram', 'ML Hayden', 'PA Patel',
       'MS Dhoni', 'KC Sangakkara', 'Yuvraj Singh', 'SM Katich',
       'IK Pathan', 'YK Pathan', 'T Kohli', 'G Gambhir', 'S Dhawan',
       'D Salunkhe', 'SK Warne', 'SK Trivedi', 'V Sehwag', 'SR Watson',
       'M Kaif', 'DS Lehmann', 'RA Jadeja', 'M Rawat', 'ST Jayasuriya',
       'L Ronchi', 'DJ Thornely', 'RV Uthappa', 'PR Shah', 'AM Nayar',
       'SM Pollock', 'Harbhajan Singh', 'S Chanderpaul', 'LRPL Taylor',
       'WP Saha', 'A Symonds', 'AS Yadav', 'SB Bangar', 'WPUJC Vaas',
       'RP Singh', 'PP Ojha', 'Y Venugopal Rao', 'AC Gilchrist',
       'VVS Laxman', 'SB Styris', 'LR Shukla', 'WA Mota', 'Kamran Akmal',
       'DPMD Jayawardene', 'S

In [ ]:
deliveries_2['bowler'].isnull().unique()

array([False])

In [ ]:
deliveries_2['bowler'].unique()

array(['AA Noffke', 'Z Khan', 'JH Kallis', 'SB Joshi', 'CL White',
       'P Kumar', 'AB Agarkar', 'SC Ganguly', 'LR Shukla', 'I Sharma',
       'AB Dinda', 'JDP Oram', 'JR Hopes', 'MS Gony', 'K Goel',
       'PP Chawla', 'WA Mota', 'IK Pathan', 'S Sreesanth', 'B Lee',
       'M Muralitharan', 'P Amarnath', 'Joginder Sharma', 'GD McGrath',
       'B Geeves', 'SK Warne', 'YK Pathan', 'D Salunkhe', 'SR Watson',
       'SK Trivedi', 'DL Vettori', 'MF Maharoof', 'MM Patel', 'R Bhatia',
       'B Akhil', 'R Vinay Kumar', 'A Nehra', 'SM Pollock', 'DS Kulkarni',
       'AM Nayar', 'Harbhajan Singh', 'ST Jayasuriya', 'WPUJC Vaas',
       'RP Singh', 'SB Styris', 'SB Bangar', 'DJ Hussey',
       'Mohammad Hafeez', 'M Kartik', 'PP Ojha', 'A Symonds',
       'Pankaj Singh', 'Mohammad Asif', 'VY Mahesh', 'Shahid Afridi',
       'MA Khote', 'DJ Bravo', 'VS Yeligati', 'D Kalyankrishna',
       'VRV Singh', 'A Kumble', 'Sohail Tanvir', 'DNT Zoysa',
       'SD Chitnis', 'Shoaib Malik', 'Yuvraj Singh',

In [ ]:
deliveries_2['batsman_runs'].isnull().unique()

array([False])

In [ ]:
deliveries_2['batsman_runs'].unique()

array([1, 0, 2, 6, 4, 5, 3])

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['extra_runs'].isnull().unique()

array([False])

In [ ]:
deliveries_2['extra_runs'].unique()

array([0, 4, 1, 2, 5, 3, 7])

In [ ]:
deliveries_2['total_runs'].isnull().unique()

array([False])

In [ ]:
deliveries_2['total_runs'].unique()

array([1, 0, 2, 6, 4, 5, 3, 7])

In [ ]:
deliveries_2['non_boundary'].isnull().unique()

array([False])

In [ ]:
deliveries_2['non_boundary'].unique()

array([0, 1])

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['is_wicket'].isnull().unique()

array([False])

In [ ]:
deliveries_2['is_wicket'].unique()

array([0, 1])

In [ ]:
deliveries_2['dismissal_kind'].isnull().unique()

array([ True, False])

In [ ]:
deliveries_2['dismissal_kind'].unique()

array([nan, 'caught', 'run out', 'bowled', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field'], dtype=object)

In [ ]:
deliveries_2['dismissal_kind'].fillna("none", inplace = True)

In [ ]:
deliveries_2['dismissal_kind'].unique()

array(['none', 'caught', 'run out', 'bowled', 'lbw', 'retired hurt',
       'stumped', 'caught and bowled', 'hit wicket',
       'obstructing the field'], dtype=object)

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['player_dismissed'].unique()

array([nan, 'RT Ponting', 'DJ Hussey', 'SC Ganguly', 'MV Boucher',
       'B Akhil', 'CL White', 'AA Noffke', 'Z Khan', 'SB Joshi',
       'JH Kallis', 'W Jaffer', 'R Dravid', 'V Kohli', 'SK Raina',
       'JDP Oram', 'PA Patel', 'ML Hayden', 'MS Dhoni', 'JR Hopes',
       'Yuvraj Singh', 'KC Sangakkara', 'K Goel', 'SK Warne', 'V Sehwag',
       'T Kohli', 'YK Pathan', 'SR Watson', 'DS Lehmann', 'M Kaif',
       'M Rawat', 'RA Jadeja', 'DJ Thornely', 'L Ronchi', 'ST Jayasuriya',
       'PR Shah', 'RV Uthappa', 'AM Nayar', 'SM Pollock', 'S Chanderpaul',
       'LRPL Taylor', 'BB McCullum', 'WP Saha', 'AS Yadav', 'A Symonds',
       'WPUJC Vaas', 'SB Bangar', 'PP Ojha', 'Y Venugopal Rao',
       'VVS Laxman', 'AC Gilchrist', 'RG Sharma', 'SB Styris',
       'Mohammad Hafeez', 'Kamran Akmal', 'DPMD Jayawardene', 'IK Pathan',
       'B Lee', 'S Sohal', 'G Gambhir', 'Shahid Afridi', 'MEK Hussey',
       'Harbhajan Singh', 'DJ Bravo', 'MA Khote', 'GC Smith',
       'D Salunkhe', 'PP Chawla',

In [ ]:
deliveries_2['player_dismissed'].isnull().unique()

array([ True, False])

In [ ]:
deliveries_2['player_dismissed']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ... 
193463    NaN
193464    NaN
193465    NaN
193466    NaN
193467    NaN
Name: player_dismissed, Length: 193468, dtype: object

In [ ]:
deliveries_2['player_dismissed'].fillna("none", inplace = True)

In [ ]:
deliveries_2['player_dismissed'].isnull().unique()

array([False])

In [ ]:
deliveries_2['player_dismissed']

0         none
1         none
2         none
3         none
4         none
          ... 
193463    none
193464    none
193465    none
193466    none
193467    none
Name: player_dismissed, Length: 193468, dtype: object

In [ ]:
deliveries_2.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
deliveries_2['fielder'].isnull().unique()

array([ True, False])

In [ ]:
deliveries_2['fielder'].unique()

array([nan, 'P Kumar', 'CL White', 'JH Kallis', 'M Kartik', 'RT Ponting',
       'WP Saha', 'AB Agarkar,WP Saha', 'BB McCullum', 'IK Pathan',
       'KC Sangakkara', 'Joginder Sharma', 'P Amarnath', 'PA Patel',
       'M Manhas', 'B Geeves', 'V Kohli', 'Z Khan', 'MV Boucher',
       'AM Nayar', 'L Ronchi', 'RG Sharma', 'SB Styris', 'AB Dinda',
       'DJ Hussey', 'SC Ganguly', 'Mohammad Hafeez,WP Saha', 'LR Shukla',
       'Mohammad Hafeez', 'A Symonds', 'PP Chawla', 'Kamran Akmal',
       'RA Jadeja,Kamran Akmal', 'MK Tiwary,KD Karthik', 'GD McGrath',
       'G Gambhir', 'AC Gilchrist', 'S Dhawan', 'KD Karthik', 'DJ Bravo',
       'S Badrinath', 'Harbhajan Singh', 'JDP Oram', 'SK Raina',
       'RA Jadeja', 'D Kalyankrishna', 'VVS Laxman,RP Singh', 'SB Bangar',
       'D Salunkhe', 'DS Kulkarni', 'DJ Bravo,L Ronchi', 'A Nehra',
       'Harbhajan Singh,L Ronchi', 'B Lee', 'RR Sarwan',
       'AM Rahane (sub)', 'Yuvraj Singh', 'M Rawat,SR Watson', 'MM Patel',
       'GC Smith', 'M Rawat

In [ ]:
deliveries_2['fielder'].fillna("none", inplace = True)

In [ ]:
deliveries_2['fielder'].isnull().unique()

array([False])

In [ ]:
deliveries_2['extras_type'].unique()

array([nan, 'byes', 'wides', 'legbyes', 'noballs', 'penalty'],
      dtype=object)

In [ ]:
deliveries_2['extras_type'].fillna("none", inplace = True)

In [ ]:
deliveries_2['extras_type'].unique()

array(['none', 'byes', 'wides', 'legbyes', 'noballs', 'penalty'],
      dtype=object)

In [ ]:
deliveries_2['batting_team'].unique()

array(['Kolkata', 'Bangalore', 'Punjab', 'Chennai', 'Rajasthan', 'Delhi',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Gujarat'], dtype=object)

In [ ]:
deliveries_2['bowling_team'].unique()

array(['Bangalore', 'Kolkata', 'Chennai', 'Punjab', 'Delhi', 'Rajasthan',
       'Mumbai', 'Hyderabad', 'Kerala', 'Pune', 'Unknown', 'Gujarat'],
      dtype=object)

In [ ]:
deliveries_2.head()

id  inning  over  ball  ... fielder extras_type batting_team  bowling_team
0  335982       1     6     5  ...    none        none      Kolkata     Bangalore
1  335982       1     6     6  ...    none        none      Kolkata     Bangalore
2  335982       1     7     1  ...    none        none      Kolkata     Bangalore
3  335982       1     7     2  ...    none        none      Kolkata     Bangalore
4  335982       1     7     3  ...    none        none      Kolkata     Bangalore

[5 rows x 18 columns]

In [ ]:
matches_2.head()

id        city        date  ...  method    umpire1         umpire2
0  335982   Bangalore  2008-04-18  ...  Normal  Asad Rauf     RE Koertzen
1  335983  Chandigarh  2008-04-19  ...  Normal  MR Benson      SL Shastri
2  335984       Delhi  2008-04-19  ...  Normal  Aleem Dar  GA Pratapkumar
3  335985      Mumbai  2008-04-20  ...  Normal   SJ Davis       DJ Harper
4  335986     Kolkata  2008-04-20  ...  Normal  BF Bowden     K Hariharan

[5 rows x 17 columns]

In [ ]:
matches_2['result'].unique()

array(['runs', 'wickets', 'tie', nan], dtype=object)

In [ ]:
matches_2['result'].fillna("No Result", inplace = True)

In [ ]:
matches_2['result'].unique()

array(['runs', 'wickets', 'tie', 'No Result'], dtype=object)

In [ ]:
Merge = pd.merge(deliveries_2,matches_2,on='id',how='inner')
Merge.head(10)

id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen
5  335982       1     7     4  ...         No  Normal  Asad Rauf  RE Koertzen
6  335982       1     7     5  ...         No  Normal  Asad Rauf  RE Koertzen
7  335982       1     7     6  ...         No  Normal  Asad Rauf  RE Koertzen
8  335982       1     8     1  ...         No  Normal  Asad Rauf  RE Koertzen
9  335982       1     8     2  ...         No  Normal  Asad Rauf  RE Koertzen

[10 rows x 34 columns]

In [ ]:
Merge.head(10)

id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen
5  335982       1     7     4  ...         No  Normal  Asad Rauf  RE Koertzen
6  335982       1     7     5  ...         No  Normal  Asad Rauf  RE Koertzen
7  335982       1     7     6  ...         No  Normal  Asad Rauf  RE Koertzen
8  335982       1     8     1  ...         No  Normal  Asad Rauf  RE Koertzen
9  335982       1     8     2  ...         No  Normal  Asad Rauf  RE Koertzen

[10 rows x 34 columns]

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              object
non_striker          object
bowler               object
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       object
player_dismissed     object
fielder              object
extras_type          object
batting_team         object
bowling_team         object
city                 object
date                 object
player_of_match      object
venue                object
neutral_venue         int64
team1                object
team2                object
toss_winner          object
toss_decision        object
winner               object
result               object
result_margin       float64
eliminator           object
method               object
umpire1              object
umpire2              object
dtype: object

In [ ]:
Merge['result_margin'].unique()

array([140.,  33.,   9.,   5.,   6.,   3.,  66.,   7.,  10.,   4.,  13.,
        45.,   8.,  29.,  18.,  23.,  41.,  12.,  65.,  25.,   1.,  14.,
       105.,  19.,  75.,  92.,  11.,  24.,   0.,  27.,  38.,  78.,  16.,
        53.,   2.,  31.,  55.,  98.,  34.,  36.,  39.,  17.,  40.,  67.,
        63.,  37.,  57.,  35.,  22.,  21.,  48.,  26.,  20.,  85.,  32.,
        76., 111.,  82.,  43.,  58.,  28.,  74.,  42.,  59.,  46.,  47.,
        86.,  44.,  87., 130.,  15.,  60.,  77.,  30.,  50.,  93.,  72.,
        62.,  97., 138.,  71., 144.,  80.,  51.,  61., 146.,  64., 102.,
       118.,  49.,  88.,  69.])

In [ ]:
Merge['eliminator'].unique() 

array(['No', 'Yes', 'NR'], dtype=object)

In [ ]:
Merge[Merge.isna().any(axis=1)]

Empty DataFrame
Columns: [id, inning, over, ball, batsman, non_striker, bowler, batsman_runs, extra_runs, total_runs, non_boundary, is_wicket, dismissal_kind, player_dismissed, fielder, extras_type, batting_team, bowling_team, city, date, player_of_match, venue, neutral_venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, eliminator, method, umpire1, umpire2]
Index: []

In [ ]:
Merge.head()

id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen

[5 rows x 34 columns]

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              object
non_striker          object
bowler               object
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       object
player_dismissed     object
fielder              object
extras_type          object
batting_team         object
bowling_team         object
city                 object
date                 object
player_of_match      object
venue                object
neutral_venue         int64
team1                object
team2                object
toss_winner          object
toss_decision        object
winner               object
result               object
result_margin       float64
eliminator           object
method               object
umpire1              object
umpire2              object
dtype: object

In [ ]:
Merge['umpire2'].unique()

array(['RE Koertzen', 'SL Shastri', 'GA Pratapkumar', 'DJ Harper',
       'K Hariharan', 'RB Tiffin', 'AM Saheba', 'MR Benson', 'IL Howell',
       'AV Jayaprakash', 'I Shivram', 'BR Doctrove', 'BG Jerling',
       'SJ Davis', 'SD Ranade', 'SJA Taufel', 'M Erasmus',
       'TH Wijewardene', 'SK Tarapore', 'S Ravi', 'HDPK Dharmasena',
       'SS Hazare', 'PR Reiffel', 'AL Hill', 'RJ Tucker', 'VA Kulkarni',
       'JD Cloete', 'BNJ Oxenford', 'S Asnani', 'S Das', 'C Shamshuddin',
       'AK Chaudhary', 'K Srinath', 'Subroto Das', 'CK Nandan',
       'NJ Llong', 'RK Illingworth', 'PG Pathak', 'CB Gaffaney',
       'K Srinivasan', 'SD Fry', 'VK Sharma', 'A Nand Kishore',
       'Nitin Menon', 'A Deshmukh', 'YC Barde', 'IJ Gould'], dtype=object)

In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              object
non_striker          object
bowler               object
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       object
player_dismissed     object
fielder              object
extras_type          object
batting_team         object
bowling_team         object
city                 object
date                 object
player_of_match      object
venue                object
neutral_venue         int64
team1                object
team2                object
toss_winner          object
toss_decision        object
winner               object
result               object
result_margin       float64
eliminator           object
method               object
umpire1              object
umpire2              object
dtype: object

In [ ]:
Merge['batsman'] = pd.Series(Merge['batsman'], dtype="string")
Merge['non_striker'] = pd.Series(Merge['non_striker'], dtype="string")
Merge['bowler'] = pd.Series(Merge['bowler'], dtype="string")
Merge['dismissal_kind'] = pd.Series(Merge['dismissal_kind'], dtype="string")
Merge['player_dismissed'] = pd.Series(Merge['player_dismissed'], dtype="string")
Merge['fielder'] = pd.Series(Merge['fielder'], dtype="string")
Merge['extras_type'] = pd.Series(Merge['extras_type'], dtype="string")
Merge['batting_team'] = pd.Series(Merge['batting_team'], dtype="string")
Merge['bowling_team'] = pd.Series(Merge['bowling_team'], dtype="string")
Merge['city'] = pd.Series(Merge['city'], dtype="string")
Merge['date'] = pd.Series(Merge['date'], dtype="string")
Merge['player_of_match'] = pd.Series(Merge['player_of_match'], dtype="string")
Merge['venue'] = pd.Series(Merge['venue'], dtype="string")
Merge['team1'] = pd.Series(Merge['team1'], dtype="string")
Merge['team2'] = pd.Series(Merge['team2'], dtype="string")
Merge['toss_winner'] = pd.Series(Merge['toss_winner'], dtype="string")
Merge['toss_decision'] = pd.Series(Merge['toss_decision'], dtype="string")
Merge['winner'] = pd.Series(Merge['winner'], dtype="string")
Merge['result'] = pd.Series(Merge['result'], dtype="string")
Merge['eliminator'] = pd.Series(Merge['eliminator'], dtype="string")
Merge['method'] = pd.Series(Merge['method'], dtype="string")
Merge['umpire1'] = pd.Series(Merge['umpire1'], dtype="string")
Merge['umpire2'] = pd.Series(Merge['umpire2'], dtype="string")




In [ ]:
Merge.dtypes

id                    int64
inning                int64
over                  int64
ball                  int64
batsman              string
non_striker          string
bowler               string
batsman_runs          int64
extra_runs            int64
total_runs            int64
non_boundary          int64
is_wicket             int64
dismissal_kind       string
player_dismissed     string
fielder              string
extras_type          string
batting_team         string
bowling_team         string
city                 string
date                 string
player_of_match      string
venue                string
neutral_venue         int64
team1                string
team2                string
toss_winner          string
toss_decision        string
winner               string
result               string
result_margin       float64
eliminator           string
method               string
umpire1              string
umpire2              string
dtype: object

In [ ]:
Merge.head()

id  inning  over  ball  ... eliminator  method    umpire1      umpire2
0  335982       1     6     5  ...         No  Normal  Asad Rauf  RE Koertzen
1  335982       1     6     6  ...         No  Normal  Asad Rauf  RE Koertzen
2  335982       1     7     1  ...         No  Normal  Asad Rauf  RE Koertzen
3  335982       1     7     2  ...         No  Normal  Asad Rauf  RE Koertzen
4  335982       1     7     3  ...         No  Normal  Asad Rauf  RE Koertzen

[5 rows x 34 columns]

In [ ]:
Merge[Merge.isna().any(axis=1)]

Empty DataFrame
Columns: [id, inning, over, ball, batsman, non_striker, bowler, batsman_runs, extra_runs, total_runs, non_boundary, is_wicket, dismissal_kind, player_dismissed, fielder, extras_type, batting_team, bowling_team, city, date, player_of_match, venue, neutral_venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, eliminator, method, umpire1, umpire2]
Index: []

In [ ]:
Merge['venue'].unique()

<StringArray>
[                           'M.Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali',
                                 'Feroz Shah Kotla',
                                 'Wankhede Stadium',
                                     'Eden Gardens',
                           'Sawai Mansingh Stadium',
        'Rajiv Gandhi International Stadium, Uppal',
                  'MA Chidambaram Stadium, Chepauk',
                       'Dr DY Patil Sports Academy',
                                         'Newlands',
                                 "St George's Park",
                                        'Kingsmead',
                                  'SuperSport Park',
                                     'Buffalo Park',
                            'New Wanderers Stadium',
                            'De Beers Diamond Oval',
                                  'OUTsurance Oval',
                                'Brabourne Stadium',
                     'Sardar Pat

In [ ]:
# from google.colab import files
# Merge.to_csv('Merged_Deliveries_and_Matches.csv')
# files.download('Merged_Deliveries_and_Matches.csv')

In [ ]:
from google.colab import files
matches_2.to_csv('Matches_After_Cleaning.csv')
files.download('Matches_After_Cleaning.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
from google.colab import files
deliveries_2.to_csv('Deliveries_After_Cleaning.csv')
files.download('Deliveries_After_Cleaning.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

# Now Exporting the final Dataset

In [ ]:

from google.colab import files
Merge.to_csv('Merged_Deliveries_and_Matches.csv')
files.download('Merged_Deliveries_and_Matches.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>